# Dockerfile (React frontend)
FROM node:18-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Serve bằng nginx
FROM nginx:alpine

# Copy custom nginx config for React SPA
COPY nginx-frontend.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist  /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
