# Dockerfile (React frontend)
FROM node:18-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Serve bằng nginx
FROM nginx:alpine


# COPY CUSTOM NGINX CONFIG

COPY nginx.conf /etc/nginx/conf.d/default.conf


COPY --from=builder /app/dist  /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
